library(data.table)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggrepel)

source("r_functions/manhattan_plots.r")
source("../QC_BipEx/r_functions_and_parameters/pretty_plotting.r")

paper_qq_plots <- function(dt, qq_labels=20,
	width=4.5, height=4, include_col=TRUE, title.hjust=0,
	include_title=TRUE, include_legend=TRUE, step=0.5, name=NULL,
	minus_log_p_max=10^(-7))
{
	
	phenotypes <- unique(dt$PHENO)
	xlim <- c(0, max(dt$p_perm))
	ylim <- c(0, max(dt$pval, -log10(minus_log_p_max)))

	max_replace_full <- max(abs(dt$log_OR[is.finite(dt$log_OR)]))

	for (phenotype in phenotypes)
	{	
		dt_tmp <- dt %>% filter(PHENO == phenotype)
		max_replace <- max(abs(dt_tmp$log_OR[is.finite(dt_tmp$log_OR)]))
		dt_tmp$log_OR[!is.finite(dt_tmp$log_OR)] <- sign(dt_tmp$log_OR[!is.finite(dt_tmp$log_OR)]) * max_replace
		
		dt_tmp <- dt_tmp %>% mutate(
			discrete_colors = case_when(
				dt_tmp$log_OR < -1 ~ "blue3",
				((dt_tmp$log_OR > -1) & (dt_tmp$log_OR <= 0)) ~ "cornflowerblue",
				((dt_tmp$log_OR > 0) & (dt_tmp$log_OR <= 1)) ~ "indianred3",
				dt_tmp$log_OR > 1 ~ "red",
				TRUE ~ "grey40"),
			size = case_when(
				dt_tmp$pval > 3 ~ 20,
				((dt_tmp$pval > -log10(0.05)) & (dt_tmp$pval <= 3)) ~ 5,
				TRUE ~ 0.5)
			)

		dt_tmp$discrete_colors <- factor(dt_tmp$discrete_colors, levels = c("red", "indianred3", "cornflowerblue", "blue3"))

		p <- create_pretty_qq_plot(
			dt_tmp, aes(x=p_perm, y=pval, color=discrete_colors),#, size=size),
			n_to_include=qq_labels, plot_title=phenotype, gradient=FALSE, 
			gradient_title=TeX("$\\log(OR)$"), save_figure=FALSE, print_p=FALSE, title.hjust=title.hjust,
			cex_labels=4, xlim=xlim, ylim=ylim, 
			legend_max_min=c(-ceiling(max_replace_full/step)*step, ceiling(max_replace_full/step)*step),
			n_legend_step=2*(ceiling(max_replace_full/step)), alpha=1)

		if (include_legend == FALSE) {
			p <- p + theme(legend.position="none")
		}

		p <- p + scale_colour_manual(name="Odds ratio",
            values = levels(dt_tmp$discrete_colors), labels=c("> 10", "1 - 10", "0.1 - 1", "< 0.1"),
			aesthetics = c("colour", "fill")) + guides(colour = guide_legend(override.aes = list(size=5)))

		if(is.null(name)) {
			# ggsave(paste0(phenotype, '_QQ.jpg'), p, width=width, height=height)
			ggsave(paste0(phenotype, '_QQ.pdf'), p, width=width, height=height)
		} else {
			# ggsave(paste0(gsub(",", "", gsub(" ", "_", phenotype)), '_', name, '_QQ.jpg'), p, width=width, height=height)
			ggsave(paste0(gsub(",", "", gsub(" ", "_", phenotype)), '_', name, '_QQ.pdf'), p, width=width, height=height)
		}

	}
}

BP_table <- "../../analysis_plots/gene_counts_qq/plots/BP_gene_fisher_MAC5_gnom_non_psych_qq.tsv"
# This (below) is generated by 19_determine_gene_symbols_and_gene_ids.py
GENE_SYMBOL_AND_ID <- "gsutil cat gs://dalio_bipolar_w1_w2_hail_02/gene_ids_and_symbols.tsv"
dt_ID <- fread(GENE_SYMBOL_AND_ID)
# hgnc <- fread("../browser_BipEx/hgnc.tsv") %>% rename("gene_symbol" = `Approved symbol`)
ensembl <- fread("ensembl_IDs_and_positions.tsv") %>% rename(ensembl_ID = `Gene stable ID`)

dt_BP <- merge(fread(BP_table), dt_ID)
# dt_BP <- merge(dt_BP, hgnc, by="gene_symbol") %>% rename(ensembl_ID = `Ensembl ID(supplied by Ensembl)`)
dt_BP <- merge(dt_BP %>% rename(ensembl_ID=gene_id), ensembl, by="ensembl_ID")
dt_BP <- dt_BP %>% rename(CHR = `Chromosome/scaffold name`, START = `Gene start (bp)`, END = `Gene end (bp)`) %>% 
	mutate(BP = (START + (END-START)/2)) %>% filter(consequence_category=="ptv")

dt_BP1 <- dt_BP %>% rename(PVAL=gnom_non_psych.is_BP1.pval) %>% 
	mutate(PHENO="Bipolar Disorder 1") %>% 
	select(PHENO, CHR, BP, PVAL, gene_symbol) 

dt_BP2 <- dt_BP %>% rename(PVAL=gnom_non_psych.is_BP2.pval) %>% 
	mutate(PHENO="Bipolar Disorder 2") %>% 
	select(PHENO, CHR, BP, PVAL, gene_symbol)

dt_BP <- dt_BP %>% rename(PVAL=gnom_non_psych.is_BP.pval) %>% 
	mutate(PHENO="Bipolar Disorder") %>% 
	select(PHENO, CHR, BP, PVAL, gene_symbol)

dt <- rbind(dt_BP, dt_BP1, dt_BP2)

# Define the max of the plot
p_min <- 10^(-7)

phenotypes <- unique(dt$PHENO)

# First, create the Manhattan plots
for (phenotype in phenotypes) {

	dt_tmp <- dt %>% filter(PHENO == phenotype)

	p <- make_manhattan_plot(
		dt_tmp[['CHR']], dt_tmp[['BP']],
		dt_tmp[['PVAL']],
		labels=dt_tmp[['gene_symbol']],
		log_p_vals=FALSE,
		significance_T=2.14e-6,
		threshold=(-log10((dt_tmp %>% arrange(PVAL) %>% select(PVAL))[20,] + .Machine$double.eps))$PVAL,
		title=phenotype,
		file=paste0(phenotype, "_manhattan"),
		save_figure=TRUE,
		title_size=22,
		two_tone=TRUE,
		colour_1="#c24100",
		colour_2="#0081c2",
		ggplot_theme=theme_classic,
		buffer=0,
		minus_log_p_max=-log10(p_min))

}

# Next, create the QQ plots
Rdatas <- c(
	"../../analysis_plots/gene_counts_qq/plots/BP_gene_fisher_MAC5_gnom_non_psych_qq_gnom_non_psych.is_BP.Rdata",
	"../../analysis_plots/gene_counts_qq/plots/BP_gene_fisher_MAC5_gnom_non_psych_qq_gnom_non_psych.is_BP1.Rdata",
	"../../analysis_plots/gene_counts_qq/plots/BP_gene_fisher_MAC5_gnom_non_psych_qq_gnom_non_psych.is_BP2.Rdata"
)
phenotypes <- c("Bipolar Disorder", "Bipolar Disorder 1", "Bipolar Disorder 2")
consequence_categories <- "ptv"

for(conseq_cat in consequence_categories)
{
	for (i in 1:length(Rdatas))
	{
		load(Rdatas[i])
		dt_QQ_tmp <- dt_plot %>% filter(consequence_category == conseq_cat) %>% select(labels, log_OR, pval, p_perm) %>% mutate(PHENO = phenotypes[i])
		if (i == 1) {
			dt_QQ <- dt_QQ_tmp
		} else {
			dt_QQ <- rbind(dt_QQ, dt_QQ_tmp)
		}
	}

	if(conseq_cat %in% c("ptv", "damaging_missense")) {
		n_labels <- ifelse(i==1, 20, 10)
	} else {
		n_labels <- NULL
	}

	paper_qq_plots(dt_QQ, name=conseq_cat, qq_labels=n_labels)
}

# Create a new plot that increases the sizes of dots for the more significant genes, and includes the ORs colours as in the QQ plot


pdf(file="~/Repositories/BipEx/paper_figures/Figure_3.pdf", width=10, height=4)
for(conseq_cat in consequence_categories)
{
	for (i in 1:length(Rdatas))
	{
		load(Rdatas[i])
		dt_QQ_tmp <- dt_plot %>% filter(consequence_category == conseq_cat) %>% select(labels, log_OR, pval, p_perm) %>% mutate(PHENO = phenotypes[i])
		dt_manhattan_tmp <- dt %>% filter(PHENO == phenotypes[i])
		dt_manhattan_tmp <- merge(dt_manhattan_tmp %>% select(-PHENO), dt_QQ_tmp %>% rename(gene_symbol=labels), by="gene_symbol")

		n_labels <- ifelse(i==1, 20, 10)

		p <- make_manhattan_plot(
			dt_manhattan_tmp[['CHR']], dt_manhattan_tmp[['BP']],
			dt_manhattan_tmp[['PVAL']],
			log_OR=dt_manhattan_tmp[['log_OR']],
			labels=dt_manhattan_tmp[['gene_symbol']],
			log_p_vals=FALSE,
			significance_T=2.14e-6,
			threshold=(-log10((dt_manhattan_tmp %>% arrange(PVAL) %>% select(PVAL))[n_labels,] + .Machine$double.eps))$PVAL,
			title=phenotypes[i],
			file=paste0(phenotypes[i], "_manhattan"),
			save_figure=FALSE,
			title_size=22,
			two_tone=FALSE,
			by_OR=TRUE,
			colour_1="#c24100",
			colour_2="#0081c2",
			ggplot_theme=theme_classic,
			buffer=1e8,
			size_by_p=TRUE,
			minus_log_p_max=-log10(p_min))
		print(p$p)
	}
}
dev.off()

